apiVersion: v1
data:
  application.properties: |-
    # This for kogito service url
    kogito.service.url=http://${quarkus.http.host}:${quarkus.http.port}

    # This is for pre-check validation
    quarkus.rest-client.elaitest_dataindex_yaml.url=${kogito.data-index.url:${kogito.service.url}}

    # This is to enable debugging of HTTP request
    quarkus.log.category.\"org.apache.http\".level=INFO

    # This is for persistence
    quarkus.flyway.migrate-at-start=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: elaitest
    sonataflow.org/workflow-app: elaitest
  name: elaitest-props
