apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  annotations:
    sonataflow.org/description: yolo2
    sonataflow.org/expressionLang: jq
    sonataflow.org/profile: dev
    sonataflow.org/version: 1.0.0-SNAPSHOT
  creationTimestamp: null
  labels:
    app: elaitest
    sonataflow.org/workflow-app: elaitest
  name: elaitest
spec:
  flow:
    annotations:
    - workflow-type/assessment
    dataInputSchema:
      failOnValidationErrors: true
      schema: schemas/elaitest-input-schema.json
    functions:
    - name: execute
      operation: service:java:io.janus.workflow.elaitest.SampleAssessment::execute
      type: custom
    - name: logOutput
      operation: sysout:INFO
      type: custom
    - name: extract
      operation: .result | flatten | map(.id)
      type: expression
    - name: checkProcessDefinitionExistence
      operation: specs/elaitest-dataindex.yaml#reactiveGraphQLHandlerPost
      type: rest
    - name: removeMissingWorkflowsFromOptions
      operation: .missingWorkflows as $f | .result | walk( if type == "object" then
        select(all($f[] != .id; .)) else . end )
      type: expression
    start:
      stateName: StartState
    states:
    - actionMode: sequential
      actions:
      - actionDataFilter:
          toStateData: .result
          useResults: true
        functionRef:
          arguments:
            sampleText: .sampleText
          invoke: sync
          refName: execute
        name: executeAction
      name: StartState
      stateDataFilter:
        output: '. +={workflowOptions: .preCheck.validatedResult}'
      transition:
        nextState: ExtractWorkflows
      type: operation
    - actionMode: sequential
      actions:
      - actionDataFilter:
          toStateData: .infrasWorkflows
          useResults: true
        functionRef:
          invoke: sync
          refName: extract
        name: ExtractWorkflowsAction
      name: ExtractWorkflows
      transition:
        nextState: QueryWorkflow
      type: operation
    - actions:
      - actionDataFilter:
          results: ${ .data.ProcessDefinitions[0].id }
          useResults: true
        functionRef:
          arguments:
            operationName: CheckProcessDefQuery
            query: 'query CheckProcessDefQuery($id: String) { ProcessDefinitions  (
              where: {id: { equal: $id} } ) { id } }'
            variables:
              id: ${ .infrasWorkflow }
          invoke: sync
          refName: checkProcessDefinitionExistence
        name: checkAction
      inputCollection: ${ .infrasWorkflows }
      iterationParam: infrasWorkflow
      mode: parallel
      name: QueryWorkflow
      outputCollection: ${ .fetchResults }
      transition:
        nextState: Check
      type: foreach
    - dataConditions:
      - condition: (.infrasWorkflows-.fetchResults | length > 0)
        transition:
          nextState: PrintError
      defaultCondition:
        transition:
          nextState: HandleNoError
      name: Check
      type: switch
    - actionMode: sequential
      actions:
      - actionDataFilter:
          useResults: true
        functionRef:
          arguments:
            message: '"workflows: \(.infrasWorkflows-.fetchResults) are not found"'
          invoke: sync
          refName: logOutput
        name: error
      name: PrintError
      stateDataFilter:
        output: '. += { missingWorkflows: (.infrasWorkflows - .fetchResults) } | del(.infrasWorkflows,
          .fetchResults)'
      transition:
        nextState: HandleError
      type: operation
    - actionMode: sequential
      actions:
      - actionDataFilter:
          toStateData: ${ .validatedResult }
          useResults: true
        functionRef:
          invoke: sync
          refName: removeMissingWorkflowsFromOptions
        name: error
      name: HandleError
      stateDataFilter:
        output: .originalResult = .result | del(.result)
      transition:
        nextState: printAction
      type: operation
    - actionMode: sequential
      actions: []
      name: HandleNoError
      stateDataFilter:
        output: .validatedResult = .result | del(.infrasWorkflows, .fetchResults)
      transition:
        nextState: printAction
      type: operation
    - actionMode: sequential
      actions:
      - actionDataFilter:
          useResults: true
        functionRef:
          arguments:
            message: .validatedResult
          invoke: sync
          refName: logOutput
      end:
        terminate: true
      name: printAction
      stateDataFilter:
        output: '{workflowOptions: .validatedResult}'
      type: operation
  podTemplate:
    container:
      resources: {}
  resources:
    configMaps:
    - configMap:
        name: 01-elaitest-resources
      workflowPath: schemas
    - configMap:
        name: 02-elaitest-resources
      workflowPath: specs
status:
  address: {}
  lastTimeRecoverAttempt: null
