apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
__RESOURCES__
namespace: sonataflow-infra

configurations:
- config/image-configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - secret.properties
    name: elaitest-secret
configMapGenerator:
  - envs:
      - config.properties
    name: elaitest-gitops

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: elaitest
images:
- name: serverless-workflow-elaitest
  newName: quay.io/gfarache/template-test
  newTag: __IMAGE_TAG__
